version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/network-socket.pool.conf:/usr/local/etc/php-fpm.d/network-socket.pool.conf
        links:
            - php
        container_name: fast_cgi_nginx

    php:
        image: prooph/php:7.2-fpm-xdebug
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:rw

        container_name: fast_cgi_app

    composer:
        image: prooph/composer:7.2
        command:  update
        working_dir:  /var/www
        volumes:
            - .:/var/www:rw
        container_name: fast_cgi_composer
